apiVersion: v1
kind: Pod
metadata:
  name: web
  namespace: default
  labels:
    name: nuxt
spec:
  containers:  
  - name: node
    image: sunny0183/nextjs-docker:latest  
    ports:
    - containerPort: 80
